package a;

/* loaded from: /tmp/jadx-10340276197810293799.dex */
public final class cx {

    /* renamed from: a, reason: collision with root package name */
    public int f86a;
    public final a.fx b;
    public final a.ex c;
    public final a.dx d;
    public final a.gx e;
    public java.util.HashMap f;

    /* JADX WARN: Type inference failed for: r0v0, types: [a.fx, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v1, types: [java.lang.Object, a.ex] */
    /* JADX WARN: Type inference failed for: r0v2, types: [java.lang.Object, a.dx] */
    /* JADX WARN: Type inference failed for: r0v3, types: [a.gx, java.lang.Object] */
    public cx() {
        fx obj = new a.fx();
        obj.f162a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ex obj2 = new a.ex();
        obj2.f140a = -1;
        obj2.b = -1;
        obj2.c = Float.NaN;
        obj2.d = Float.NaN;
        this.c = obj2;
        dx obj3 = new a.dx();
        obj3.f111a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = -1;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = 0.5f;
        obj3.u = 0.5f;
        obj3.v = null;
        obj3.w = -1;
        obj3.x = 0;
        obj3.y = 0.0f;
        obj3.z = -1;
        obj3.A = -1;
        obj3.B = -1;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = -1;
        obj3.G = -1;
        obj3.H = -1;
        obj3.I = -1;
        obj3.J = -1;
        obj3.K = -1;
        obj3.L = -1;
        obj3.M = -1;
        obj3.N = -1;
        obj3.O = -1.0f;
        obj3.P = -1.0f;
        obj3.Q = 0;
        obj3.R = 0;
        obj3.S = 0;
        obj3.T = 0;
        obj3.U = -1;
        obj3.V = -1;
        obj3.W = -1;
        obj3.X = -1;
        obj3.Y = 1.0f;
        obj3.Z = 1.0f;
        obj3.a0 = -1;
        obj3.b0 = 0;
        obj3.c0 = -1;
        obj3.g0 = false;
        obj3.h0 = false;
        obj3.i0 = true;
        this.d = obj3;
        a.gx obj4 = (gx) new fx();
        /* TODO: jadx type unresolved, defaulted to Object */
        obj4.f195a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = 0.0f;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = false;
        obj4.l = 0.0f;
        this.e = obj4;
        this.f = new java.util.HashMap();
    }

    public final void a(a.yw ywVar) {
        a.dx dxVar = this.d;
        ywVar.d = dxVar.g;
        ywVar.e = dxVar.h;
        ywVar.f = dxVar.i;
        ywVar.g = dxVar.j;
        ywVar.h = dxVar.k;
        ywVar.i = dxVar.l;
        ywVar.j = dxVar.m;
        ywVar.k = dxVar.n;
        ywVar.l = dxVar.o;
        ywVar.p = dxVar.p;
        ywVar.q = dxVar.q;
        ywVar.r = dxVar.r;
        ywVar.s = dxVar.s;
        ((android.view.ViewGroup.MarginLayoutParams) ywVar).leftMargin = dxVar.C;
        ((android.view.ViewGroup.MarginLayoutParams) ywVar).rightMargin = dxVar.D;
        ((android.view.ViewGroup.MarginLayoutParams) ywVar).topMargin = dxVar.E;
        ((android.view.ViewGroup.MarginLayoutParams) ywVar).bottomMargin = dxVar.F;
        ywVar.x = dxVar.N;
        ywVar.y = dxVar.M;
        ywVar.u = dxVar.J;
        ywVar.w = dxVar.L;
        ywVar.z = dxVar.t;
        ywVar.A = dxVar.u;
        ywVar.m = dxVar.w;
        ywVar.n = dxVar.x;
        ywVar.o = dxVar.y;
        ywVar.B = dxVar.v;
        ywVar.P = dxVar.z;
        ywVar.Q = dxVar.A;
        ywVar.E = dxVar.O;
        ywVar.D = dxVar.P;
        ywVar.G = dxVar.R;
        ywVar.F = dxVar.Q;
        ywVar.S = dxVar.g0;
        ywVar.T = dxVar.h0;
        ywVar.H = dxVar.S;
        ywVar.I = dxVar.T;
        ywVar.L = dxVar.U;
        ywVar.M = dxVar.V;
        ywVar.J = dxVar.W;
        ywVar.K = dxVar.X;
        ywVar.N = dxVar.Y;
        ywVar.O = dxVar.Z;
        ywVar.R = dxVar.B;
        ywVar.c = dxVar.f;
        ywVar.f720a = dxVar.d;
        ywVar.b = dxVar.e;
        ((android.view.ViewGroup.MarginLayoutParams) ywVar).width = dxVar.b;
        ((android.view.ViewGroup.MarginLayoutParams) ywVar).height = dxVar.c;
        java.lang.String str = dxVar.f0;
        if (str != null) {
            ywVar.U = str;
        }
        ywVar.setMarginStart(dxVar.H);
        ywVar.setMarginEnd(dxVar.G);
        ywVar.a();
    }

    public final java.lang.Object clone() {
        a.cx cxVar = new a.cx();
        a.dx dxVar = cxVar.d;
        dxVar.getClass();
        a.dx dxVar2 = this.d;
        dxVar.f111a = dxVar2.f111a;
        dxVar.b = dxVar2.b;
        dxVar.c = dxVar2.c;
        dxVar.d = dxVar2.d;
        dxVar.e = dxVar2.e;
        dxVar.f = dxVar2.f;
        dxVar.g = dxVar2.g;
        dxVar.h = dxVar2.h;
        dxVar.i = dxVar2.i;
        dxVar.j = dxVar2.j;
        dxVar.k = dxVar2.k;
        dxVar.l = dxVar2.l;
        dxVar.m = dxVar2.m;
        dxVar.n = dxVar2.n;
        dxVar.o = dxVar2.o;
        dxVar.p = dxVar2.p;
        dxVar.q = dxVar2.q;
        dxVar.r = dxVar2.r;
        dxVar.s = dxVar2.s;
        dxVar.t = dxVar2.t;
        dxVar.u = dxVar2.u;
        dxVar.v = dxVar2.v;
        dxVar.w = dxVar2.w;
        dxVar.x = dxVar2.x;
        dxVar.y = dxVar2.y;
        dxVar.z = dxVar2.z;
        dxVar.A = dxVar2.A;
        dxVar.B = dxVar2.B;
        dxVar.C = dxVar2.C;
        dxVar.D = dxVar2.D;
        dxVar.E = dxVar2.E;
        dxVar.F = dxVar2.F;
        dxVar.G = dxVar2.G;
        dxVar.H = dxVar2.H;
        dxVar.I = dxVar2.I;
        dxVar.J = dxVar2.J;
        dxVar.K = dxVar2.K;
        dxVar.L = dxVar2.L;
        dxVar.M = dxVar2.M;
        dxVar.N = dxVar2.N;
        dxVar.O = dxVar2.O;
        dxVar.P = dxVar2.P;
        dxVar.Q = dxVar2.Q;
        dxVar.R = dxVar2.R;
        dxVar.S = dxVar2.S;
        dxVar.T = dxVar2.T;
        dxVar.U = dxVar2.U;
        dxVar.V = dxVar2.V;
        dxVar.W = dxVar2.W;
        dxVar.X = dxVar2.X;
        dxVar.Y = dxVar2.Y;
        dxVar.Z = dxVar2.Z;
        dxVar.a0 = dxVar2.a0;
        dxVar.b0 = dxVar2.b0;
        dxVar.c0 = dxVar2.c0;
        dxVar.f0 = dxVar2.f0;
        int[] iArr = dxVar2.d0;
        if (iArr != null) {
            dxVar.d0 = java.util.Arrays.copyOf(iArr, iArr.length);
        } else {
            dxVar.d0 = null;
        }
        dxVar.e0 = dxVar2.e0;
        dxVar.g0 = dxVar2.g0;
        dxVar.h0 = dxVar2.h0;
        dxVar.i0 = dxVar2.i0;
        a.ex exVar = cxVar.c;
        exVar.getClass();
        a.ex exVar2 = this.c;
        exVar2.getClass();
        exVar.f140a = exVar2.f140a;
        exVar.b = exVar2.b;
        exVar.d = exVar2.d;
        exVar.c = exVar2.c;
        a.fx fxVar = cxVar.b;
        fxVar.getClass();
        a.fx fxVar2 = this.b;
        fxVar2.getClass();
        fxVar.f162a = fxVar2.f162a;
        fxVar.c = fxVar2.c;
        fxVar.d = fxVar2.d;
        fxVar.b = fxVar2.b;
        a.gx gxVar = cxVar.e;
        gxVar.getClass();
        a.gx gxVar2 = this.e;
        gxVar2.getClass();
        gxVar.f195a = gxVar2.f195a;
        gxVar.b = gxVar2.b;
        gxVar.c = gxVar2.c;
        gxVar.d = gxVar2.d;
        gxVar.e = gxVar2.e;
        gxVar.f = gxVar2.f;
        gxVar.g = gxVar2.g;
        gxVar.h = gxVar2.h;
        gxVar.i = gxVar2.i;
        gxVar.j = gxVar2.j;
        gxVar.k = gxVar2.k;
        gxVar.l = gxVar2.l;
        cxVar.f86a = this.f86a;
        return cxVar;
    }
}
